config/routes.rb
Rails.application.routes.draw do
  resources :visits, except:[:edit, :update] do
    collection do
      get 'reserved_datetimes' => "visits#reserved_datetimes"
    end
  end

  devise_for :patients # adresy Devise dla pacjentów
  devise_for :doctors, :class_name => 'Doctor', :controllers => {:registrations => "doctors/registrations"} do
    get "doctor/sign_up" => "doctor/registrations#new", :as => :new_doctor_registration # obsługa rejestracji kont lekarzy przez odpowiedni kontroler
  end
  resources :doctors, only: [:index] do# adres listy lekarzy
    resources :worktimes, only: [] do
      collection do
        post 'edit' => 'worktimes#edit'
        put 'update' => 'worktimes#update', :as => 'update'
        get '' => 'worktimes#index', :as => ''
      end
    end
  end

  get 'static_pages/home' # adres strony głównej
  get 'static_pages/about' # adres strony o przychodni
  root 'static_pages#home' # ustalenie strony głównej

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
#   end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  validates :visit_date, :patient_id, :doctor_id, presence: true
  validate :visit_date_cannot_be_in_the_past
  validates_uniqueness_of :visit_date, scope: :doctor_id

  private
  def visit_date_cannot_be_in_the_past
    if visit_date.present? && visit_date < Date.today
      errors.add(:visit_date, "Niepoprawna data wizyty")
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # before_action :set_visit, only: [:show, :edit, :update, :destroy]
  before_action :set_visit, only: [:show, :destroy]
  before_action :authenticate_patient!, only: [:new, :create, :destroy]

  def reserved_datetimes
    puts "RESERVED"
    if request.xhr?
      doctor = ActiveSupport::JSON.decode(CGI.unescapeHTML(params[:doctor_id]))
      visit_date = CGI.unescapeHTML(params[:visit_date]).to_date
      @visits = Visit.where(doctor_id: doctor).where('DATE(visit_date) = ?', visit_date)
    end
  end

  def index
    if request.xhr?
      # if request.path.start_with?("visits")
      # doctor = ActiveSupport::JSON.decode(CGI.unescapeHTML(params[:doctor_id]))
      # visit_date = CGI.unescapeHTML(params[:visit_date]).to_date
      # @visits = Visit.where(doctor_id: doctor).where('DATE(visit_date) = ?', visit_date)
      # else
      if doctor_signed_in?
        @future_visits = Visit.where(doctor_id: current_doctor.id)
      else
        @future_visits = Visit.where(patient_id: current_patient.id)
      end
      # end
      # @future_visits = Visit.where(patient_id: current_patient.id)
    else
      if patient_signed_in?
        @past_visits = Visit.where(patient_id: current_patient.id).where('visit_date < ?', DateTime.now)
        @future_visits = Visit.where(patient_id: current_patient.id).where('visit_date > ?', DateTime.now)
      end
      if doctor_signed_in?
        if current_doctor.admin?
          @past_visits = Visit.all.where('visit_date < ?', DateTime.now)
          @future_visits = Visit.all.where('visit_date > ?', DateTime.now)
        else
          @past_visits = Visit.where(doctor_id: current_doctor.id).where('visit_date < ?', DateTime.now)
          @future_visits = Visit.where(doctor_id: current_doctor.id).where('visit_date > ?', DateTime.now)
        end
      end
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    if !patient_signed_in?
      if !doctor_signed_in?
        redirect_to root_path
      else
        if @visit.doctor_id!=current_doctor.id
          redirect_to root_path
        end
      end
    else
      if @visit.patient_id!=current_patient.id
        then redirect_to root_path
      end
    end
  end

  # GET /visits/new
  def new
    @visit = Visit.new
    @doctor = Doctor.find(params[:doctor_id])
    @appointments = []
    @doctor.visits.each do |a| @appointments << a.visit_date.strftime("%Y-%m-%d %H:%M") end
      @start_times = []
      @end_times = []
      @doctor.worktimes.sort.each do |w| @start_times << w.start_time.strftime("%H").to_i end
        @doctor.worktimes.sort.each do |w| @end_times << w.end_time.strftime("%H").to_i end
        end

        # GET /visits/1/edit
        # def edit
        # end

        # POST /visits
        # POST /visits.json
        def create
          @visit = Visit.new(visit_params)
          @visit.doctor_id = params[:doctor_id]
          @visit.patient_id = current_patient.id
          visit_date = @visit.visit_date
          if visit_date.nil?
            respond_to do |format|
              format.html { redirect_to visits_path, :flash => { :error => 'Błędna data. Spróbuj ponownie.' }}
              format.json { render json: @visit.errors, status: :unprocessable_entity }
            end
          else
            day_of_week = visit_date.wday # nazwa dnia tygodnia
            the_day_worktime = Worktime.where(doctor_id:params[:doctor_id]).where(weekday: Worktime::VALID_WEEKDAYS[day_of_week-1]).first

            # walidacja zgodności z czasem pracy
            if visit_date.strftime("%HH") >= the_day_worktime.start_time.strftime("%HH") && visit_date.strftime("%HH") < the_day_worktime.end_time.strftime("%HH")
              respond_to do |format|
                if @visit.save
                  format.html { redirect_to visits_path, :flash => { :success => 'Wizyta została zarejestrowana.' }}
                  format.json { render :show, status: :created, location: @visit }
                else
                  format.html { redirect_to visits_path, :flash => { :error => 'Błędna data. Spróbuj ponownie.' }}
                  format.json { render json: @visit.errors, status: :unprocessable_entity }
                end
              end
            else
              respond_to do |format|
                format.html { redirect_to visits_path, :flash => { :error => 'Błędna data. Spróbuj ponownie.' }}
                format.json { render json: @visit.errors, status: :unprocessable_entity }
              end
            end
          end
        end

        # PATCH/PUT /visits/1
        # PATCH/PUT /visits/1.json
        # def update
        #   respond_to do |format|
        #     if @visit.update(visit_params)
        #       format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        #       format.json { render :show, status: :ok, location: @visit }
        #     else
        #       format.html { render :edit }
        #       format.json { render json: @visit.errors, status: :unprocessable_entity }
        #     end
        #   end
        # end

        # DELETE /visits/1
        # DELETE /visits/1.json
        def destroy
          if @visit.patient_id!=current_patient.id
            then redirect_to root_path
          else
            @visit.destroy
            respond_to do |format|
              format.html { redirect_to visits_url, notice: 'Wizyta została anulowana.' }
              format.json { head :no_content }
            end
          end
        end

        private
        # Use callbacks to share common setup or constraints between actions.
        def set_visit
          @visit = Visit.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def visit_params
          params.require(:visit).permit(:visit_date, :patient_id, :doctor_id)
        end
      end

app/helpers/visits_helper.rb
module VisitsHelper
  def visits_ajax_previous_month_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
  end
  def visits_ajax_next_month_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  end
  # def visits_ajax_previous_day_link
  #   ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
  # end
  # def visits_ajax_next_day_link
  #   ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  # end
end

app/views/visits/_calendar.html.erb
<%= month_calendar attribute: :visit_date, events: @future_visits,
previous_link: visits_ajax_previous_month_link, next_link: visits_ajax_next_month_link do |date, visits| %>
<%= link_to date.day, visits_path(start_date: date) %>
<% if false %>
<% visits.each do |v| %>
<div>
  <%= link_to v.visit_date.strftime("%H:%M"), v %>
</div>
<% end %>
<% end %>
<div>
  <% if visits.count>0 %>
  <!-- <%= visits.count.to_s %> -->
  <span class="glyphicon glyphicon-star-empty"></span>
  <%end%>
</div>
<% end %>

app/views/visits/_daily_calendar.html.erb
<%= calendar number_of_days: 1, attribute: :visit_date, events: @future_visits do |date, visits| %>
<% if false %>
<%= date.day %>
<% end %>
<% if visits.count==0 %>
Brak wizyt w tym dniu.
<% else %>
  <% visits.each do |v| %>
    <div>
      <% if doctor_signed_in? %>
        <%= v.visit_date.strftime("%H:%M") + " - " + v.patient.name %>
      <% else %>
        <% if false %>
        <%= link_to v.visit_date.strftime("%H:%M")+v.doctor.name, v %>
        <% end %>
        <%= v.visit_date.strftime("%H:%M") + " - " + v.doctor.name %>
      <% end %>
    </div>
    <% end %>
  <% end %>
<% end %>

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
<%= errors_for(@visit) %>

<%= content_tag "div", id: "times", data: { start_times: @start_times, end_times: @end_times } do %><% end %>

<%= form.label "Lekarz" %>
<div class="form-group disabled">
  <%= text_field_tag 'doctor_name', @doctor.name, :disabled => true%>
</div>
<%= hidden_field_tag 'doctor_id', params[:doctor_id] %>
<%= form.label :visit_date %>
<div class="form-group">
  <input type='text' class="form-control" id='visit_date_time_picker' name='visit[visit_date]'/><br/>
</div>
<div class="actions">
  <%= form.submit "Zapisz się na wizytę", class: 'btn btn-primary'%>
</div>
<% end %>

app/views/visits/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default devise-bs">
      <div class="panel-heading"><h4>Lista wizyt</h4></div>
      <div class="panel-body">
        <%= render partial: "daily_calendar", locals: {events: @future_visits} %>
        <% if !doctor_signed_in? %>
        <%= link_to 'Zarejestruj nową wizytę', doctors_path, class: 'btn btn-primary' %>
        <% end %>
        <br>
        <br>
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="pill" href="#future">Umówione wizyty</a></li>
          <li><a data-toggle="pill" href="#past">Minione wizyty</a></li>
        </ul>
        <div class="tab-content">
          <div id="future" class="tab-pane fade in active">
            <div class="table-responsive">
              <% if @future_visits.nil? %>
              <%= link_to new_patient_session_path do %>Zaloguj się<% end %>, aby zobaczyć listę umówionych wizyt lub zarejestrować nową.
              <% else %>
              <table class=" table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Data wizyty</th>
                    <% if doctor_signed_in? %>
                    <th>Pacjent</th>
                    <% end %>
                    <% if patient_signed_in? || (doctor_signed_in? && current_doctor.admin?)%>
                    <th>Lekarz</th>
                    <th>Specjalizacje</th>
                    <th>Anulowanie</th>
                    <% end %>
                  </tr>
                </thead>

                <tbody>
                  <% @future_visits.each do |visit| %>
                  <tr>
                    <td><%= visit.visit_date.strftime("%d/%m/%Y %H:%M") %></td>
                    <% if doctor_signed_in? %>
                    <td><%= visit.patient.name %></td>
                    <% end %>
                    <% if patient_signed_in? || (doctor_signed_in? && current_doctor.admin?) %>
                    <td><%= visit.doctor.name %></td>
                    <td><% visit.doctor.specializations.each do |s| %>
                      <%= s.appellation %><br>
                      <% end %></td>
                      <td><%= link_to 'Odwołaj wizytę', visit, class: 'btn btn-sm btn-warning', method: :delete, data: { confirm: 'Czy na pewno chcesz anulować wizytę?' } %></td>
                      <% end %>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
                <% end %>
              </div>
            </div>
            <div id="past" class="tab-pane fade">
              <div class="table-responsive">
                <% if @past_visits.nil? %>
                <%= link_to new_patient_session_path do %>Zaloguj się<% end %>, aby zobaczyć listę umówionych wizyt lub zarejestrować nową.
                <% else %>
                <table class=" table table-striped table-hover">
                  <thead>
                    <tr>
                      <th>Data wizyty</th>
                      <% if doctor_signed_in? %>
                      <th>Pacjent</th>
                      <% end %>
                      <% if patient_signed_in? || (doctor_signed_in? && current_doctor.admin?)%>
                      <th>Lekarz</th>
                      <th>Specjalizacje</th>
                      <% end %>
                    </tr>
                  </thead>

                  <tbody>
                    <% @past_visits.each do |visit| %>
                    <tr>
                      <td><%= visit.visit_date.strftime("%d/%m/%Y %H:%M") %></td>
                      <% if doctor_signed_in? %>
                      <td><%= visit.patient.name %></td>
                      <% end %>
                      <% if patient_signed_in? || (doctor_signed_in? && current_doctor.admin?) %>
                      <td><%= visit.doctor.name %></td>
                      <td><% visit.doctor.specializations.each do |s| %>
                        <%= s.appellation %><br>
                        <% end %></td>
                        <%# link_to 'Szczegóły', visit %>
                        <% end %>
                      </tr>
                      <% end %>
                    </tbody>
                  </table>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% if (patient_signed_in? || doctor_signed_in?) %>
      <div class="col-sm-6">
        <div class="panel panel-default devise-bs">
          <div class="panel-heading"><h4>Kalendarz wizyt</h4></div>
          <div class="panel-body">
            <div id="visits_calendar">
              <%= render partial: "calendar", locals: {events: @future_visits} %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/visits/index.js.erb
$("#visits_calendar").html("<%= escape_javascript render(partial: "calendar", locals: {events: @future_visits}) %>");

app/views/visits/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>Nowa wizyta</h4>
      </div>
      <div class="panel-body">
        <div id='brak_wolnych_godzin' class="alert alert-info" style="display: none;">Brak wolnych godzin w tym dniu. Wybierz inny termin.</div>
        <%= render 'form', visit: @visit %>
      </div>
    </div>
  </div>
</div>

app/views/visits/show.html.erb
<p>
  <strong>Data wizyty:</strong>
  <%= @visit.visit_date.strftime("%d/%m/%Y %H:%M") %>
</p>
<p>
  <strong>Pacjent:</strong>
  <%= Patient.find(@visit.patient_id).name %>
</p>
<p>
  <strong>Lekarz:</strong>
  <%= Doctor.find(@visit.doctor_id).name %>
</p>