config/routes.rb
Rails.application.routes.draw do
  resources :visits, except:[:edit, :update] do
    collection do
      get 'reserved_datetimes' => "visits#reserved_datetimes"
    end
  end

  devise_for :patients # adresy Devise dla pacjentów
  devise_for :doctors, :class_name => 'Doctor', :controllers => {:registrations => "doctors/registrations"} do
    get "doctor/sign_up" => "doctor/registrations#new", :as => :new_doctor_registration # obsługa rejestracji kont lekarzy przez odpowiedni kontroler
  end
  resources :doctors, only: [:index] do# adres listy lekarzy
    resources :worktimes, only: [] do
      collection do
        post 'edit' => 'worktimes#edit'
        put 'update' => 'worktimes#update', :as => 'update'
        get '' => 'worktimes#index', :as => ''
      end
    end
  end

  get 'static_pages/home' # adres strony głównej
  get 'static_pages/about' # adres strony o przychodni
  root 'static_pages#home' # ustalenie strony głównej

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
#   end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_and_belongs_to_many :specializations
  has_many :worktimes, dependent: :destroy
  has_many :visits, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :phone, presence: true
end

app/models/worktime.rb
class Worktime < ApplicationRecord
  belongs_to :doctor
  validates :weekday, :start_time, :end_time, :doctor_id, presence: true
  validates_uniqueness_of :weekday, scope: :doctor_id
  VALID_WEEKDAYS = ["poniedziałek", "wtorek", "środa", "czwartek", "piątek"]
  validates :weekday, :inclusion => {:in => Worktime::VALID_WEEKDAYS}
end

app/controllers/worktimes_controller.rb
class WorktimesController < ApplicationController
  before_action :check_doctor, only: [:index, :edit, :update]
  DAY_ORDER = %w(poniedziałek wtorek środa czwartek piątek)

  def index
    @worktimes = Worktime.where(:doctor_id => params[:doctor_id])
    @worktimes = @worktimes.sort_by{|wd| DAY_ORDER.index(wd.weekday)}
  end

  def edit
    @worktimes = Worktime.find(Doctor.find(params[:doctor_id]).worktimes.ids)
    @worktimes = @worktimes.sort_by{|wd| DAY_ORDER.index(wd.weekday)}
  end

  def update
    @worktimes = Worktime.update(params[:worktimes].keys, params[:worktimes].values)
    @worktimes.reject! { |w| w.errors.empty? }
    if @worktimes.empty?
      redirect_to :action => "index"
    else
      flash[:notice] = "Proszę poprawić błędne godziny pracy"
      render "edit"
    end
  end

  private

  def check_doctor
    if !(doctor_signed_in?)
      redirect_to root_path
    elsif !(current_doctor.id==params[:doctor_id].to_i)
      redirect_to root_path
    end
  end
end

app/views/worktimes/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4> Edycja godzin pracy: </h4>
      </div>
      <div class="panel-body">
        <%= form_tag update_doctor_worktimes_path, method: :put do %>
        <div class="table-responsive">
          <table class="table">
            <tr>
            <% @worktimes.each do |worktime| %>
                <%= fields_for "worktimes[]", worktime do |f| %>
                  <td>
                    <%= worktime.weekday %>
                    <div class="field">
                      <% if worktime.start_time.nil? %>
                        <%= f.time_field :start_time, value: "09:00"%>
                      <% else %>
                        <%= f.time_field :start_time, value: worktime.start_time.strftime("%H:%M")%>
                      <% end %>
                    </div>
                    <div class="field">
                      <% if worktime.end_time.nil? %>
                        <%= f.time_field :end_time, value: "17:00"%>
                      <% else %>
                        <%= f.time_field :end_time, value: worktime.end_time.strftime("%H:%M") %>
                      <% end %>
                    </div>
                  </td>
                <% end %>
              <% end %>
            </tr>
          </table>
        </div>
        <div class="actions">
          <%= submit_tag "Zmień godziny pracy", class: 'btn btn-primary' %>
        </div>
         <% end %>
        </div>
      </div>
    </div>
  <div class="col-sm-6"></div>
</div>

app/views/worktimes/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading"><h4>Godziny pracy lekarza: </h4></div>
        <div class="panel-body">
          <div class="table-responsive">
            <%= form_tag edit_doctor_worktimes_path do %>
              <table class="table table-striped table-hover table-bordered">
                <thead>
                  <tr>
                    <th>Dzień tygodnia</th>
                    <th>Rozpoczęcie pracy</th>
                    <th>Zakończenie pracy</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                      <% @worktimes.each do |worktime| %>
                    <td><%= worktime.weekday %></td>
                    <td><%= worktime.start_time.strftime("%H:%M") %></td>
                    <td><%= worktime.end_time.to_formatted_s(:time)  %></td>

                    <%= hidden_field_tag "worktime_ids[]", worktime.id %>
                  </tr>
                  <% end %>
                </tbody>
              </table>

            <%= submit_tag "Zmień godziny pracy", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>