config/routes.rb
Rails.application.routes.draw do
  resources :visits, except:[:edit, :update] do
    collection do
      get 'reserved_datetimes' => "visits#reserved_datetimes"
    end
  end

  devise_for :patients # adresy Devise dla pacjentów
  devise_for :doctors, :class_name => 'Doctor', :controllers => {:registrations => "doctors/registrations"} do
    get "doctor/sign_up" => "doctor/registrations#new", :as => :new_doctor_registration # obsługa rejestracji kont lekarzy przez odpowiedni kontroler
  end
  resources :doctors, only: [:index] do# adres listy lekarzy
    resources :worktimes, only: [] do
      collection do
        post 'edit' => 'worktimes#edit'
        put 'update' => 'worktimes#update', :as => 'update'
        get '' => 'worktimes#index', :as => ''
      end
    end
  end

  get 'static_pages/home' # adres strony głównej
  get 'static_pages/about' # adres strony o przychodni
  root 'static_pages#home' # ustalenie strony głównej

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
#   end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Przełącz panel nawigacyjny</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Przychodni@', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
		<li><%= link_to 'O stronie', static_pages_about_url %></li>
    <% if patient_signed_in? || doctor_signed_in? %>
    <li><%= link_to 'Wizyty', visits_path %></li>
    <% end %>
    <li><%= link_to "Lista lekarzy", doctors_url %></li>
      </ul>

		<ul class="nav navbar-nav navbar-right">
      <% if patient_signed_in? %>
        <!-- <li><p class="navbar-text" id="custom-navbar-text"><%= current_patient.name.upcase %></p> -->
        <li><%= link_to current_patient.name.upcase, edit_patient_registration_path %> </li>
        <li><%= link_to destroy_patient_session_path, :method => :delete do %>Wyloguj<% end %></li>
      <% elsif doctor_signed_in? %>
        <!-- <li><p class="navbar-text" id="custom-navbar-text"><%= current_doctor.name.upcase %></p> -->
        <% if current_doctor.try(:admin?) %>
          <li><%= link_to "Zarejestruj konto Lekarza" ,new_doctor_registration_path %></li>
        <% end %>
        <li><%= link_to "Godziny pracy", doctor_worktimes_path(current_doctor) %>
        <li><%= link_to current_doctor.name.upcase, edit_doctor_registration_path %> </li>
        <li><%= link_to destroy_doctor_session_path, :method => :delete do %>Wyloguj<% end %></li>

      <% else %>
        <li><%= link_to "Zarejestruj konto Pacjenta" ,new_patient_registration_path %></li>
        <li><%= link_to new_patient_session_path do %>Zaloguj (Pacjent)<% end %></li>
        <li><%= link_to new_doctor_session_path do %>Zaloguj (Lekarz)<% end %></li>
      <% end %>
		</ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Przychodni@ </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/i18n/defaults-pl_PL.min.js"></script>
</head>
<body>
  <%= render "layouts/header" %>
  <main class="container">
    <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <%= value %>
      </ul>
    </div>
    <% end %>
    <%= yield %>
  </main>
</body>
</html>